############################################################
# #
#web访问端口号 约定：8088
# #
###########################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
############################################################
# #
#配置数据源信息
# #
###########################################################
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123
############################################################
# #
#mybatis 配置
# #
###########################################################
mybatis:
  type-aliases-package: com.imooc.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
############################################################


file:
  imageUserFaceLocation: "D:\\project\\foodie\\foodie-dev\\foodie-dev-api\\src\\main\\resources\\images\\"
  imageServerUrl: "http://localhost:8088/faces/"